services:
 
  #  5G EDGE NODE
  #  Runs inside the UPF network namespace so it can see ogstun traffic.
 
  
  5g-edge-node:
    build: ./5g-edge-node
    container_name: 5g-edge-node
    network_mode: "container:upf"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - ./evidence:/evidence
      - ./evaluation:/evaluation
    environment:
      - CAPTURE_IFACE=ogstun
      - EVIDENCE_DIR=/evidence
      - UE_SUBNET=192.168.100.0/24
      - USE_RFC3161=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  
  #  IOT TRAFFIC GENERATOR
  # container:nr_ue" attaches this container to the UE's network namespace so it shares uesimtun0.
  iot-traffic-generator:
    build: ./iot-traffic-generator
    container_name: reaf-traffic
    network_mode: "container:nr_ue"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./evaluation:/evaluation
    environment:
      - UE_TUNNEL_IFACE=uesimtun0
      - TARGET_IP=${TARGET_IP:-192.168.100.1}
      - MODE=${MODE:-synthetic}
      - SEND_INTERVAL=2
      - REPLAY_SPEED=1.0
      - MAX_RUNTIME_SECONDS=1200
      - PCAP_PATH=pre-selected/replay_pcaps_contiguous/Benign_Final/BenignTraffic_contiguous_sample.pcap
    restart: "no"
